[package]
name = "fns_enclave"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "Function node service, trusted gateway in front of the actual worker."
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fns_enclave"
crate-type = ["staticlib"]

[features]
default = []
mesalock_sgx = ["sgx_tstd", "mesatee_core/mesalock_sgx", "fns_proto/mesalock_sgx", "tms_internal_proto/mesalock_sgx", "tms_internal_client/mesalock_sgx", "tdfs_internal_client/mesalock_sgx"]
cov = ["sgx_cov"]

[dependencies]
cfg-if               = { version = "0.1.9" }
lazy_static          = { version = "1.0.2", features = ["spin_no_std"] }
serde                = { version = "1.0.92" }
serde_derive         = { version = "1.0.92" }
serde_json           = { version = "1.0.39" }
wasmi                = { version = "0.6.0" }
wabt                 = { version = "0.6.0" }
base64               = { version = "0.10.1" }
itertools            = { version = "0.8.0", default-features = false }
log                  = { version = "0.4.7", features = ["max_level_trace"] }
env_logger           = { version = "0.7.1" }
image                = { version = "0.22.1" }
ring                 = { version = "0.16.5" }
uuid                 = { version = "0.7.4", features = ["v4"] }

mesatee_core         = { version = "0.1.0" }

fns_proto            = { path = "../proto", optional = true }
tms_internal_client  = { path = "../../tms/internal/client", optional = true }
tms_internal_proto   = { path = "../../tms/internal/proto", optional = true }
tdfs_internal_client = { path = "../../tdfs/internal/client", optional = true }

sgx_cov              = { version = "0.1.0", optional = true }
sgx_tstd             = { version = "1.0.9", features = ["net", "backtrace"], optional = true }
sgx_types            = { version = "1.0.9" }
gbdt                 = { git = "https://github.com/mesalock-linux/gbdt-rs", package = "gbdt_sgx", features = ["input", "enable_training"] }
rusty-machine =  { version = "0.5.4" }
